RIGHT_ARROW = "➡️"
LEFT_ARROW = "⬅️"
INFO = "ℹ️"
WHALE = "🐳"
NO_1, NO_2, NO_3, NO_4, NO_5, NO_6, NO_7, NO_8, NO_10 = "1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣", "6️⃣", "7️⃣", "8️⃣️", "🔟"
HIT, STAND = "✅", "🟥"
OK = "🆗"
